services:
  db:
    image: postgres:17.2-alpine3.21
    container_name: postgres_container
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root123
      POSTGRES_DB: iot
    volumes:
      - ./data:/var/lib/postgresql/iot/data
    ports:
      - 5432:5432

volumes:
  db:
    driver: local
